### ISSUE TITLE
下载直接运行出错

### ISSUE THREAD

**Issue by wangkun19930608** [yAnXImIN/weiboPicDownloader#5]
直接运行出错,编译差几个架包,希望能够全面一下.
Exception in thread "main" java.lang.UnsupportedClassVersionError: weibo/WeiboDownloader :
 Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
Could not find the main class: weibo.WeiboDownloader. Program will exit.

**Comment by yAnXImIN** [comment]
你的jdk版本不對，建议升级
