### ISSUE TITLE
下载没反应，设置没问题

### ISSUE THREAD

**Issue by hiredy** [yAnXImIN/weiboPicDownloader#9]
下载没反应，设置没问题，不知道具体什么情况！
反馈一下，感谢，已star

**Comment by yAnXImIN** [comment]
分析的时间可能比较长，耐心等待即可;想看具体情况可以用命令行启动（jar -jar wb.jar），在控制台有具体日志；后期考虑加一个gui的进度条。

**Comment by hiredy** [comment]
java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
        at weibo.WeiboUtils.getImgURL(WeiboUtils.java:108)
        at weibo.WeiboUtils.getAllImgURL(WeiboUtils.java:91)
        at weibo.WeiboDownloader.downloadCli(WeiboDownloader.java:51)
        at weibo.MainGui$1$1.run(MainGui.java:114)
        at java.lang.Thread.run(Unknown Source)
解析出现异常， 请稍候再试！

看到了这个问题

**Comment by yAnXImIN** [comment]
能把账号名字给我看下吗 yanximin@foxmail.com
